{
 "title": "Compute Node Allocation",
 "tags": [
  "Long Term Metrics (2 Year Retention)"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "options": {
    "content": "## Overview\n\nThis dashboard provides an overview of your scheduler allocation during the selected time period. Note: All totals also include any nodes currently unavailable due to maintenance or onboarding.\n\n- The graphs to the right provide an overview over time of your total cluster resource versus that allocated by your scheduler.\n- The table below represents the average allocation of each resource on a per node basis."
   }
  },
  {
   "title": "Core Allocation",
   "type": "timeseries",
   "description": "The number of cores allocated versus the total number of cores in the cluster. (Total includes any nodes unavailable due to maintenance or onboarding).",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(max by (node) (slurm_node_cpu_total))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(max by (node) (slurm_node_cpu_alloc))",
     "legendFormat": "Allocated"
    }
   ]
  },
  {
   "title": "Allocation by Node",
   "type": "table",
   "description": "The average allocation in % of the total cores, memory and GPUs (where applicable) per node over the selected time period. Note: does not account for any outage due to maintenance or onboarding.",
   "gridPos": { "h": 23, "w": 10, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum_over_time(max by (node) (slurm_node_cpu_alloc)[$__range]) / sum_over_time(max by (node) (slurm_node_cpu_total)[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum_over_time(max by (node) (slurm_node_mem_alloc)[$__range]) / sum_over_time(max by (node) (slurm_node_mem_total)[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum_over_time(max by (node) (slurm_node_gpu_alloc)[$__range]) / sum_over_time(max by (node) (slurm_node_gpu_total)[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Allocation",
   "type": "timeseries",
   "description": "The amount of memory allocated versus the total amount of memory in the cluster. (Total includes any nodes unavailable due to maintenance or onboarding).",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "sum(max by (node) (slurm_node_mem_total))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(max by (node) (slurm_node_mem_alloc))",
     "legendFormat": "Allocated"
    }
   ]
  },
  {
   "title": "GPU Allocation",
   "type": "timeseries",
   "description": "The number of GPUs allocated versus the total number of GPUs in the cluster. (Total includes any nodes unavailable due to maintenance or onboarding).",
   "gridPos": { "h": 11, "w": 14, "x": 10, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(max by (node) (slurm_node_gpu_total))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(max by (node) (slurm_node_gpu_alloc))",
     "legendFormat": "Allocated"
    }
   ]
  },
  {
   "title": "Core Allocation",
   "type": "timeseries",
   "description": "The percentage of cores allocated versus the average CPU usage of the cluster. (Totals include any nodes unavailable due to maintenance or onboarding).",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(max by (node) (slurm_node_cpu_alloc)) / sum(max by (node) (slurm_node_cpu_total))) * 100",
     "legendFormat": "Allocated Cores (%)"
    },
    { "expr": "cluster_cpu_usage", "legendFormat": "Average CPU Usage (%)" }
   ]
  },
  {
   "title": "Memory Allocation",
   "type": "timeseries",
   "description": "The percentage of memory allocated versus the average memory usage of the cluster. (Totals include any nodes unavailable due to maintenance or onboarding).",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(max by (node) (slurm_node_mem_alloc)) / sum(max by (node) (slurm_node_mem_total))) * 100",
     "legendFormat": "Allocated Memory (%)"
    },
    { "expr": "cluster_memory_usage", "legendFormat": "Average Memory Usage (%)" }
   ]
  }
 ]
}