{
 "title": "Compute Node Metrics - View Individual Node Information",
 "description": "Used to monitor individual node metrics",
 "tags": [
  "Short Term Metrics (30d retention)"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(node_exporter_build_info{node_type=\"compute\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "System Uptime",
   "type": "stat",
   "description": "System uptime since last boot.",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "CPU Usage（5m）",
   "type": "gauge",
   "description": "Average CPU usage over the last 5 minutes.",
   "gridPos": { "h": 6, "w": 4, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "CPU I/O Wait（5m）",
   "type": "gauge",
   "description": "Average CPU I/O wait over the last 5 minutes.",
   "gridPos": { "h": 6, "w": 4, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[5m])) * 100"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "description": "Current memory usage.",
   "gridPos": { "h": 6, "w": 4, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (instance) ((1 - (node_memory_MemAvailable_bytes{instance=~\"$node\"} / (node_memory_MemTotal_bytes{instance=~\"$node\"})))* 100)"
    }
   ]
  },
  {
   "title": "Filesystem Usage",
   "type": "table",
   "description": "Current usage of each filesystem.",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext4|xfs\"}"
    },
    {
     "expr": "1-(node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"})"
    },
    {}
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores.",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"$node\", mode='system'}) by (cpu))"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "description": "Total available system memory.",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "description": "1m, 5m and 15m load averages.",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance) (node_load1{instance=~\"$node\"})",
     "legendFormat": "1m"
    },
    {
     "expr": "sum by (instance) (node_load5{instance=~\"$node\"})",
     "legendFormat": "5m"
    },
    {
     "expr": "sum by (instance) (node_load15{instance=~\"$node\"})",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Total disk space",
   "type": "piechart",
   "description": "Total disk space available by partition.",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes {instance=~\"$node\",fstype=~\"ext4|xfs\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "CPU usage, disk I/O operations per second take time（%）",
   "type": "timeseries",
   "description": "node_disk_io_time_seconds_total：\nThe number of milliseconds the disk spends on input/output operations. This value is the accumulated value.（Milliseconds Spent Doing I/Os）\n\nirate(node_disk_io_time_seconds_total[1m])：\nCalculate the rate per second: (last value - last previous value) / timestamp difference, that is, the percentage of time that the disk spends on I/O operations in 1 second.",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (instance) (avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"system\"}[1m])))",
     "legendFormat": "System"
    },
    {
     "expr": "sum by (instance) (avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"user\"}[1m])))",
     "legendFormat": "User"
    },
    {
     "expr": "sum by (instance) (avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[1m])))",
     "legendFormat": "Iowait"
    },
    {
     "expr": "sum by (instance, device) (irate(node_disk_io_time_seconds_total{instance=~\"$node\"}[1m]))",
     "legendFormat": "{{device}}_% of I/O operations per second"
    }
   ]
  },
  {
   "title": "Memory information",
   "type": "timeseries",
   "description": "Memory usage over the selected time period.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance) (node_memory_MemTotal_bytes{instance=~\"$node\"})",
     "legendFormat": "Total Memory"
    },
    {
     "expr": "sum by (instance) (node_memory_MemTotal_bytes{instance=~\"$node\"} - node_memory_MemAvailable_bytes{instance=~\"$node\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum by (instance) (node_memory_MemAvailable_bytes{instance=~\"$node\"})",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Disk read and write rate（IOPS）",
   "type": "timeseries",
   "description": "Reads completed: Reads per second per disk partition\n\nWrites completed: Number of writes per second per disk partition\n\nIO now Number of input/output requests being processed per disk partition per second",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum by (instance, device) (irate(node_disk_reads_completed_total{instance=~\"$node\"}[1m]))",
     "legendFormat": "{{device}}_read"
    },
    {
     "expr": "sum by (instance, device) (irate(node_disk_writes_completed_total{instance=~\"$node\"}[1m]))",
     "legendFormat": "{{device}}_write"
    }
   ]
  },
  {
   "title": "Disk read and write capacity",
   "type": "timeseries",
   "description": "Read bytes The number of bits read per second per disk partition\nWritten bytes The number of bits written per second per disk partition",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (instance, device) (irate(node_disk_read_bytes_total{instance=~\"$node\"}[1m]))",
     "legendFormat": "{{device}}_read"
    },
    {
     "expr": "sum by (instance, device) (irate(node_disk_written_bytes_total{instance=~\"$node\"}[1m]))",
     "legendFormat": "{{device}}_write"
    }
   ]
  },
  {
   "title": "Disk IO read and write time",
   "type": "timeseries",
   "description": "Read time ms Number of seconds per disk partition read operation\n\nWrite time ms Number of seconds spent per disk partition write operation\n\nIO time ms Number of seconds spent per disk partition input/output operation\n\n IO time weighted Weighted seconds spent per disk partition input/output operation",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (instance, device) (irate(node_disk_read_time_seconds_total{instance=~\"$node\"}[1m]))",
     "legendFormat": "{{device}}_read"
    },
    {
     "expr": "sum by (instance, device) (irate(node_disk_write_time_seconds_total{instance=~\"$node\"}[1m]))",
     "legendFormat": "{{device}}_write"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "description": "Network traffic per interface.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (instance, device) (irate(node_network_receive_bytes_total{instance=~'$node',device!~'tap.*'}[5m])*8)",
     "legendFormat": "{{device}}_in download"
    },
    {
     "expr": "sum by (instance, device) (irate(node_network_transmit_bytes_total{instance=~'$node',device!~'tap.*'}[5m])*8)",
     "legendFormat": "{{device}}_out upload"
    }
   ]
  },
  {
   "title": "TCP Connection situation",
   "type": "timeseries",
   "description": "CurrEstab - TCP connections with current state ESTABLISHED or CLOSE-WAIT\n\nActiveOpens - TCP average connections that have been converted from CLOSED state to SYN-SENT state (within 1 minute)\n\nPassiveOpens - Directly from LISTEN state The average number of TCP connections to SYN-RCVD state (within 1 minute)\n\nTCP_all oc - the number of TCP sockets allocated (established, applied to sk_buff)\n\nTCP_inuse - in use (listening The number of TCP sockets \n\nTCP_tw - the number of TCP connections waiting to be closed",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance, device) (node_netstat_Tcp_CurrEstab{instance=~'$node'})",
     "legendFormat": "ESTABLISHED"
    },
    {
     "expr": "sum by (instance, device) (node_sockstat_TCP_tw{instance=~'$node'})",
     "legendFormat": "TCP_tw"
    },
    {
     "expr": "sum by (instance, device) (irate(node_netstat_Tcp_ActiveOpens{instance=~'$node'}[1m]))",
     "legendFormat": "ActiveOpens"
    },
    {
     "expr": "sum by (instance, device) (irate(node_netstat_Tcp_PassiveOpens{instance=~'$node'}[1m]))",
     "legendFormat": "PassiveOpens"
    },
    {
     "expr": "sum by (instance, device) (node_sockstat_TCP_alloc{instance=~'$node'})",
     "legendFormat": "TCP_alloc"
    },
    {
     "expr": "sum by (instance, device) (node_sockstat_TCP_inuse{instance=~'$node'})",
     "legendFormat": "TCP_inuse"
    }
   ]
  },
  {
   "title": "Hardware Temperature",
   "type": "timeseries",
   "description": "Hardware Temperature sensor readings where available.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum by (instance, chip, sensor) (node_hwmon_temp_celsius{instance=\"$node\"})",
     "legendFormat": "{{chip}} {{sensor}}"
    }
   ]
  }
 ]
}