{
 "title": "Power Trends",
 "tags": [
  "Long Term Metrics (2 Year Retention)"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "pue", "label": "PUE", "query": "1.2" },
   { "name": "kwh_cost", "label": "kWh Cost £", "query": "0.18" }
  ]
 },
 "panels": [
  {
   "title": "Estimated Power Usage",
   "type": "stat",
   "description": "Total estimated power usage over the selected time period (including PUE factor).",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(cluster_power_usage[$__range])) * $pue",
     "legendFormat": "Cluster Power Usage"
    }
   ]
  },
  {
   "title": "Estimated Power Cost",
   "type": "stat",
   "description": "Total estimated power cost over the selected time period (including PUE factor).",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(sum_over_time(cluster_power_usage[$__range])) * $pue) * ($kwh_cost / 1000)",
     "legendFormat": "Cluster Power Usage"
    }
   ]
  },
  {
   "title": "Estimated Idle Power Cost",
   "type": "stat",
   "description": "Total estimated idle power cost over the selected time period (including PUE factor).",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(sum_over_time(cluster_power_usage{state=\"idle\"}[$__range])) * $pue) * ($kwh_cost / 1000)",
     "legendFormat": "Cluster Power Usage"
    }
   ]
  },
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "options": {
    "content": "This dashboard provides an overview of the estimated power usage of your cluster.\n\nData is estimated based on the power reported from the server management controllers and therefore does not include cooling overhead. The Power Usage Effectiveness variable can be adjusted to estimate this (default 20%). "
   }
  },
  { "title": "Graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Estimated Power Usage",
   "type": "timeseries",
   "description": "Estimated total and idle power usage across the selected time period (includes PUE factor).",
   "gridPos": { "h": 19, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum(cluster_power_usage) * $pue",
     "legendFormat": "Cluster Power Usage"
    },
    {
     "expr": "sum(cluster_power_usage{state=\"idle\"}) * $pue",
     "legendFormat": "Idle Power Usage"
    }
   ]
  },
  {
   "title": "Cluster Load",
   "type": "timeseries",
   "description": "Average cluster load across the selected time period.",
   "gridPos": { "h": 19, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "cluster_load_avg", "legendFormat": "Average Load" }
   ]
  }
 ]
}