{
 "title": "User Metrics",
 "tags": [
  "Short Term Metrics (30d retention)"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "user",
    "label": "User",
    "query": {
     "query": "label_values({__name__=~\"node_user_storage_quota_files_used|node_user_storage_quota_blocks_used|node_user_storage_quota_blocks_grace|node_user_storage_quota_blocks_limit|node_user_storage_quota_blocks_quota|node_user_storage_quota_files_grace|node_user_storage_quota_files_limit|node_user_storage_quota_files_quota\"},user)"
    }
   },
   {
    "name": "account",
    "label": "Account",
    "query": {
     "query": "label_values(slurm_job_meta{user=\"$user\"},account)"
    }
   },
   {
    "name": "partition",
    "label": "Partition",
    "query": {
     "query": "label_values(slurm_job_meta{account=\"$account\"},partition)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard is designed to offer insights into per user filesystem quotas, and Slurm job metrics"
   }
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Total Jobs",
   "type": "piechart",
   "description": "Total jobs terminated in the selected period.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 11 }
   ]
  },
  {
   "title": "Average CPU Utilisation",
   "type": "stat",
   "description": "Average CPU utilisation across all jobs terminated in the selected time period.",
   "gridPos": { "h": 4, "w": 6, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "panelId": 11 }
   ]
  },
  {
   "title": "Job Allocations by CPUs",
   "type": "barchart",
   "description": "Number of jobs by CPUs allocated.",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "panelId": 11 }
   ]
  },
  {
   "title": "Average Memory Utilisation",
   "type": "stat",
   "description": "Average maximum memory utilisation across all jobs terminated in the selected time period.",
   "gridPos": { "h": 4, "w": 6, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "panelId": 11 }
   ]
  },
  {
   "title": "Quota Overview (Blocks)",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 16 },
   "targets": [
    { "panelId": 33 }
   ]
  },
  {
   "title": "Quota Overview (Files)",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 16 },
   "targets": [
    { "panelId": 35 }
   ]
  },
  {
   "title": "Average Job Wait Time",
   "type": "stat",
   "description": "Average wait time across all jobs terminated in the selected time period.",
   "gridPos": { "h": 4, "w": 6, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "panelId": 11 }
   ]
  },
  {
   "title": "Job Allocations by Nodes",
   "type": "barchart",
   "description": "Number of jobs by nodes allocated.",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "panelId": 11 }
   ]
  },
  {
   "title": "Average Job Run Time",
   "type": "stat",
   "description": "Average run time across all jobs terminated in the selected time period.",
   "gridPos": { "h": 4, "w": 6, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "panelId": 11 }
   ]
  },
  { "title": "Job Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Job Efficiency",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "last_over_time(slurm_job_meta{job=\"slurm-job\", account=~\"$account\", partition=~\"$partition\", user=~\"$user\", state!~\"FAILED\", cpu_eff!=\"Infinity\", mem_util!=\"Infinity\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Quotas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Storage Quotas (Blocks)",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "last_over_time({__name__=~\"node_user_storage_quota_blocks_used|node_user_storage_quota_blocks_quota|node_user_storage_quota_blocks_limit|node_user_storage_quota_blocks_grace\", user=\"$user\", node_type=\"core\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage Quotas (Files)",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "last_over_time({__name__=~\"node_user_storage_quota_files_used|node_user_storage_quota_files_quota|node_user_storage_quota_files_limit|node_user_storage_quota_files_grace\", user=\"$user\", node_type=\"core\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}